### ISSUE TITLE
Update to graphql-java:18.x

### ISSUE THREAD

**Issue by itd-shu** [setchy/graphql-java-kickstart-federation-example#80]
Hi,

we are trying to update to
    implementation("com.graphql-java-kickstart:graphql-spring-boot-starter:13.0.0")
    implementation("com.graphql-java:graphql-java:18.3")
    implementation("com.apollographql.federation:federation-graphql-java-support:2.0.1")

from 
    implementation("com.graphql-java-kickstart:graphql-spring-boot-starter:12.0.0")
    implementation("com.graphql-java:graphql-java:17.3")
    implementation("com.apollographql.federation:federation-graphql-java-support:2.0.2")

However, we get the following error:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.kickstart.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is graphql.kickstart.tools.SchemaClassScannerError: Expected a user-defined GraphQL scalar type with name 'FieldSet' but found none!
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 123 common frames omitted
Caused by: graphql.kickstart.tools.SchemaClassScannerError: Expected a user-defined GraphQL scalar type with name 'FieldSet' but found none!
	at graphql.kickstart.tools.SchemaClassScanner.validateAndCreateResult(SchemaClassScanner.kt:170)
	at graphql.kickstart.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:106)
	at graphql.kickstart.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:156)
	at graphql.kickstart.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:200)
	at graphql.kickstart.autoconfigure.tools.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:129)
	at graphql.kickstart.autoconfigure.tools.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$47953816.CGLIB$schemaParser$0(<generated>)
	at graphql.kickstart.autoconfigure.tools.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$47953816$$FastClassBySpringCGLIB$$b0007e0c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at graphql.kickstart.autoconfigure.tools.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$47953816.schemaParser(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 124 common frames omitted
```

Do you have a working example on how to upgrade to graphql-java:18.x?

**Comment by setchy** [comment]
Hi @itd-shu - there is an open issue for this in graphql-java-tools - https://github.com/graphql-java-kickstart/graphql-java-tools/issues/664

**Comment by itd-shu** [comment]
> Hi @itd-shu - there is an open issue for this in graphql-java-tools - [graphql-java-kickstart/graphql-java-tools#664](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/664)
> 
> I'd encourage you to follow that issue

Thank you for pointing this out to me!
